Neos:
  SymfonyMailer:
    mailer:
      dsn: 'fd-mailer'

FormatD:
  Mailer:
    smtpTransport:
      host: '%env:SMTP_HOST%'
      encryption: false
      port: ''
      username: ''
      password: ''
    localEmbed: false
    attachEmbeddedImages: false
    interceptAll:
      active: false
      recipients: []
      noInterceptPatterns: []
    bccAll:
      active: false
      recipients: []
    defaultFrom:
      address: 'example@example.com'
      name: 'Example'