
FormatD:
  Mailer:
    localEmbed: false
    interceptAll:
      active: false
      recipients: []
    bccAll:
      active: false
      recipients: []
    defaultFrom:
      address: 'example@example.com'
      name: 'Example'