FormatD:
  Mailer:
    site:
      siteNodeName: 'format-d-website'
      contentRepositoryId: 'default'
    dsn: 'smtp://user:pass@smtp.example.com:25'
    localEmbed: false
    attachEmbeddedImages: false
    interceptAll:
      active: false
      recipients: []
      noInterceptPatterns: []
    bccAll:
      active: false
      recipients: []
    defaultFrom:
      address: 'example@example.com'
      name: 'Example'
    templateNodes:
      test: ''
