Neos:
  Flow:
    log:
      psr3:
        Neos\Flow\Log\PsrLoggerFactory:
          MailerLogger:
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/Mailer.log'
                severityThreshold: '%LOG_INFO%'
                createParentDirectories: true
                maximumLogFileSize: 1048576
                logFilesToKeep: 1
